source 'https://rubygems.org'

# Bundle edge Rails instead: gem 'rails', github: 'rails/rails'
gem 'rails', '~> 5.1.4'
# Use Puma as the app server
gem 'puma', '~> 3.7'
# Use SCSS for stylesheets
gem 'sass-rails', '~> 5.0'
# Use Uglifier as compressor for JavaScript assets
gem 'uglifier', '>= 1.3.0'
# Use CoffeeScript for .coffee assets and views
gem 'coffee-rails', '~> 4.2'
# Turbolinks makes navigating your web application faster. Read more: https://github.com/turbolinks/turbolinks
gem 'turbolinks', '~> 5'
# gem for bootstrap integration
gem 'bootstrap', '~> 4.0.0.alpha6'
# Haml is a templating engine for HTML.
gem 'haml'
gem 'jquery-rails'
gem 'rest-client', '~> 2.0', '>= 2.0.2'

gem 'optimizely-sdk', git: 'https://github.com/optimizely/ruby-sdk'
# To use a ruby hash as a readonly datasource for an ActiveRecord-like model.
gem 'active_hash'

# Windows does not include zoneinfo files, so bundle the tzinfo-data gem
gem 'tzinfo-data', platforms: [:mingw, :mswin, :x64_mingw, :jruby]
